package main.java;

/**
 * Any farm animal
 * @author jjbaker
 *
 */
public abstract class Animal extends Asset{
    
    //How many acres does it take up
    private double landNeeded;
    //how much revenue produced in a day
    private int producesProfit;
    //cost to purchase animal
    private int cost;
    //cycles to mature
    private final int TIME_TO_MATURE = 3;
    //cycles to die
    private final int AGE_TO_DIE = 14;
    //age of animal
    private int age;
    //chance to procreate
    private double procreateChance;
    
    /**
     * Sets required land, and base profit per animal
     * @param l land
     * @param p profit
     */
    /*
    public Animal(float l, int p, int c) {
        //LAND_NEEDED = l;
        PRODUCES_PROFIT = p;
        COST = c;
    }
    */
    
    /**
     *  Sets the amount of land this animal occupies
     * @param land needed as a double
     */
    protected void setLandNeeded(double land) {
        landNeeded = land;
    }
    
    /**
     * Sets how much that kind of animal costs
     * @param cost
     */
    protected void setCost(int cost) {
        this.cost = cost;
    }
    
    /**
     * Sets the profit of this animal
     * @param profit generated by this animal
     */
    protected void setProfit(int profit) {
        this.producesProfit = profit;
    }
    
    /**
     * initiates age - should set to 0. Only for subclass use
     * @param int age
     */
    protected void setAge(int age) {
        this.age = age;
    }
    
    /**
     * sets the animals chance to procreate on each 4th cycle
     * @param p chance to procreate
     */
    protected void setChanceToProcreate(double p) {
        procreateChance = p;
    }
    
    /**
     * Increase age of the animal by 1
     */
    public void incrementAge() {
        age++;
    }
    
    /**
     * Gets the land needed
     * @return double the amount of land this animal occupies
     */
    public double getLandNeeded() {
        return landNeeded;
    }
    
    /**
     * Returns the cost to purchase this animal
     * @return
     */
    public int getCost() {
        return cost;
    }
    
    /**
     * Get age of animal in cycles
     * @return
     */
    public int getAge() {
        return age;
    }
    
    
}
