/**
 * Parent for all asset types. Contains and manages attributes that 
 * all Farm Assets share. Also has some creation methods.
 */
package main.java;

import java.util.Random;

import exceptions.AssetAlreadyDeadException;

public abstract class Asset {
        
    //How many acres does it take up
    private double landNeeded;
    //how much revenue produced in its cycle
    private int profit;
    //cost to purchase asset
    private int cost;
    //disease death rate
    private double diseaseDeathRate;
    //state context for this asset
    private final AssetStateContext sc = new AssetStateContext();
    //harvest strategy
    private final HarvestStrategy HARVEST_STRATEGY;
    
    static Random rand = new Random();
    
    
    public Asset(int c, int p, double l, double deathRate, HarvestStrategy hs) {
        landNeeded = l;
        cost = c;
        profit = p;
        diseaseDeathRate = deathRate;
        HARVEST_STRATEGY = hs;
    }
       
    /**
     *  Sets the amount of land this animal occupies
     * @param land needed as a double
     */
    protected void setLandNeeded(double land) {
        landNeeded = land;
    }
    
    /**
     * Sets how much that kind of animal costs
     * @param cost
     */
    protected void setCost(int cost) {
        this.cost = cost;
    }
    
    /**
     * Sets the profit of this animal
     * @param profit generated by this animal
     */
    protected void setProfit(int profit) {
        this.profit = profit;
    }
    /**
     * Gets the land needed
     * @return double the amount of land this animal occupies
     */
    public double getLandNeeded() {
        return landNeeded;
    }
    
    /**
     * Returns the cost to purchase this animal
     * @return
     */
    public int getCost() {
        return cost;
    }
    
    /**
     * Returns the profit this asset produces
     * @return
     */
    public int getProfit() {
        return profit;
    }
    
    /**
     * Calls harvest() from the appropriate HarvestStrategy object 
     */
    public void harvest() {
        HARVEST_STRATEGY.harvest(this);
    }
    
    /**
     * TODO: May not need this.... 
     * @return a state context to be utilized by control class
     */
    public AssetStateContext getStateContext() {
        return sc;
    }
    
    public boolean isAlive() {
        return sc.isAlive();
    }
    
    public boolean isDiseased() {
        return sc.isDiseased();
    }
    
    /**
     * Set state of asset to diseased
     * @throws AssetAlreadyDeadException Asset is already dead. You cannot change state
     */
    public void setDiseased() throws AssetAlreadyDeadException {
        sc.setState(new StateDiseased());
    }
    
    /**
     * Set state of the asset to dead
     * @throws AssetAlreadyDeadException Asset is already dead. You cannot change state
     */
    public void setDead() throws AssetAlreadyDeadException{
        sc.setState(new StateDead());
    }
    
    /**
     * Sets the state of the asset to alive
     * @throws AssetAlreadyDeadException Asset is already dead. You cannot change state
     */
    public void setAlive() throws AssetAlreadyDeadException {
        if(sc.isDiseased()) {
            throw new AssetAlreadyDeadException();
        }
        sc.setState(new StateAlive());
    }
    
    public void setAliveReorder() {
        sc.setState(new StateAlive());
    }
    
}
