package main.java;

public abstract class Asset {
    
    //How many acres does it take up
    private double landNeeded;
    //how much revenue produced in its cycle
    private int profit;
    //cost to purchase asset
    private int cost;
    //Strategy DP - how this asset gets harvested
    private HarvestStrategy harvestStrategy;
    //disease death rate
    private double diseaseDeathRate;
    //state context for this asset
    private final AssetStateContext sc = new AssetStateContext();
    
    
    public Asset(int c, int p, double l, double deathRate) {
        landNeeded = l;
        cost = c;
        profit = p;
        diseaseDeathRate = deathRate;
    }
    
    /**
     *  Sets the amount of land this animal occupies
     * @param land needed as a double
     */
    protected void setLandNeeded(double land) {
        landNeeded = land;
    }
    
    /**
     * Sets how much that kind of animal costs
     * @param cost
     */
    protected void setCost(int cost) {
        this.cost = cost;
    }
    
    /**
     * Sets the profit of this animal
     * @param profit generated by this animal
     */
    protected void setProfit(int profit) {
        this.profit = profit;
    }
    /**
     * Gets the land needed
     * @return double the amount of land this animal occupies
     */
    public double getLandNeeded() {
        return landNeeded;
    }
    
    /**
     * Returns the cost to purchase this animal
     * @return
     */
    public int getCost() {
        return cost;
    }
    
    /**
     * Returns the profit this asset produces
     * @return
     */
    public int getProfit() {
        return profit;
    }
    
    /**
     * Sets the HarvestStrategy for this Asset
     * @param hs
     */
    public void setHarvestStrategy(HarvestStrategy hs) {
        this.harvestStrategy = hs;
    }
    
    /**
     * Calls harvest() from the appropriate HarvestStrategy object 
     */
    public void harvest() {
        harvestStrategy.harvest(this);
    }
    
    /**
     * TODO: May not need this.... 
     * @return a state context to be utilized by control class
     */
    public AssetStateContext getStateContext() {
        return sc;
    }
    
    public void doDay() {
        
    }
    
}
